---

- name: Update system
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Check if docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: docker_installed.rc != 0

# apparently its needed for docker?
# https://github.com/docker/for-linux/issues/1199
- name: Install apparmor
  when: not docker_installed
  register: apparmor
  ansible.builtin.apt:
    name: apparmor
    state: present

- name: Install aptitude using apt
  when: not docker_installed
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true
    force_apt_get: true

- name: Install required system packages
  when: not docker_installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: [
    'apt-transport-https',
    'ca-certificates',
    'curl',
    'software-properties-common',
    'python3-pip',
    'virtualenv',
    'python3-setuptools'
  ]

- name: Add docker gpg apt key
  when: not docker_installed
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository
  when: not docker_installed
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Update apt and install docker-ce
  when: not docker_installed
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: [
    'docker-ce',
    'docker-ce-cli',
    'containerd.io',
    'docker-compose'
  ]

- name: Install docker module for python
  when: not docker_installed
  ansible.builtin.apt:
    name: python3-docker
    state: present
